### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by carman191** [Monish-2304/AI_Image_Generator#1]
getting this error

TypeError: Cannot read properties of undefined (reading 'forEach')
    at HTMLButtonElement.getImages (script.js:51:13)

**Comment by Monish-2304** [comment]
> getting this error
> 
> TypeError: Cannot read properties of undefined (reading 'forEach')
>     at HTMLButtonElement.getImages (script.js:51:13)

Voice feature works only for Chrome browser, and I do hope you have put your API key at start.
